sudo: required

language: node_js
node_js:
- "10.11.0"

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - travis_wait yarn package-dev-linux
